=== WolfeeTJ/scheduler-engine-doc/enginedoc-common/src/main/resources/com/sos/scheduler/enginedoc/common/messages.xsd
<?xml version="1.0"?>

<xsd:schema 
    xmlns:xsd          = "http://www.w3.org/2001/XMLSchema"
    elementFormDefault = "qualified">

    <xsd:annotation>
        <xsd:documentation xml:lang="de">
            $Id: messages.xsd 12973 2007-09-09 11:10:05Z jz $
            Schema f√ºr Programm-Meldungen
        </xsd:documentation>
    </xsd:annotation>


    <xsd:element name="messages">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="cplusplus" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:attribute name="namespace" type="xsd:NMTOKEN"/>
                    </xsd:complexType>
                </xsd:element>

                <xsd:choice maxOccurs="unbounded">
                    <xsd:element name="message" type="message" maxOccurs="unbounded"/>
                    <xsd:element name="messages" type="messages" maxOccurs="unbounded"/>
                </xsd:choice>
            </xsd:sequence>

            <xsd:attribute name="name" type="xsd:NMTOKEN" use="required"/>
            <xsd:attribute name="include"/>
            <xsd:attribute name="title"/>
            <xsd:attribute name="base_dir"/>
            <xsd:attribute name="package" use="required"/>
            <xsd:attribute name="author"/>
            <xsd:attribute name="date"/>
        </xsd:complexType>

    </xsd:element>


    <xsd:complexType name="messages">
        <xsd:sequence>
            <xsd:element name="message" type="message" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="message">
        <xsd:sequence>
            <xsd:element name="text" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="title">
                            <xsd:complexType mixed="true">
                                <xsd:sequence minOccurs="0" maxOccurs="unbounded">
                                    <xsd:choice>
                                        <xsd:element name="p1"/>
                                        <xsd:element name="p2"/>
                                        <xsd:element name="p3"/>
                                        <xsd:element name="p4"/>
                                        <xsd:element name="br"/>
                                    </xsd:choice>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="description" minOccurs="0"/>
                    </xsd:sequence>
                    <xsd:attribute ref="xml:lang" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>

        <xsd:attribute name="code" type="xsd:string"/>
        <xsd:attribute name="weight" default="error" type="xsd:NMTOKEN"/>
        <xsd:attribute name="object" type="xsd:string"/>

    </xsd:complexType>

</xsd:schema>

=== WolfeeTJ/scheduler-engine-doc/kernel/src/main/doc/doc.en/messages/charset_messages.xml
<?xml version="1.0"?>
<?xml-stylesheet href="../scheduler.xsl" type="text/xsl"?>

<messages 
    xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation = "../zschimmer/messages.xsd"
    name     = "charset_messages"
    base_dir = "../" 
    package  = "Charset"
    author   = "$Author: jz $"
    date     = "$Date: 2012-06-12 21:42:49 +0200 (Di, 12 Jun 2012) $"
>
    <!--xmlns = "http://www.zschimmer.com/2006/program_messages"-->
    <!--xsi:schemaLocation = "http://www.zschimmer.com/2006/messages.xsd ../zschimmer/messages.xsd"-->

    <!-- <title> ohne Zeilenwechsel schreiben!  Also: <title>text ...</title> -->

    <cplusplus namespace="zschimmer"/>


    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~FEHLER-MELDUNGEN-->

    <messages>
        <message code="Z-CHARSET-001">
            <text xml:lang="en">
                <title>Unknown character encoding: <p1/></title>
            </text>
            <text xml:lang="de">
                <title>Unbekannte Zeichen-Codierung: <p1/></title>
            </text>
        </message>

        <message code="Z-CHARSET-002">
            <text xml:lang="en">
                <title>Missing character encoding</title>
            </text>
            <text xml:lang="de">
                <title>Zeichen-Codierung ist nicht angegeben</title>
            </text>
        </message>
    </messages>

</messages>
